### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by dovlabfs** [vitalpoltava/Star-Rating#6]
Stars are not showing in IE11. Hover works, value changes, but no stars are shown.

**Comment by vitalpoltava** [comment]
Thanks for a note. Will investigate..

**Comment by vitalpoltava** [comment]
Looks like it is working ok on IE11 for me. I tried [here](https://plnkr.co/edit/wzLYRVv7uXc7TjA8oeDQ?p=preview).

**Comment by vitalpoltava** [comment]
![2016-06-04 10 03 33](https://cloud.githubusercontent.com/assets/1306647/15798525/a63d7658-2a3b-11e6-84f4-cba39029180c.png)

**Comment by dovlabfs** [comment]
I still don't see the stars in IE11, I tried on 3 PCs
![prscr](https://cloud.githubusercontent.com/assets/19717415/15799082/f66ffe7e-2a50-11e6-9164-266c3dfaae0b.png)
.

**Comment by dovlabfs** [comment]
It's working fine in Firefox, Chrome and Edge.

**Comment by vitalpoltava** [comment]
Well, this is strange... I tried on my Mac's VM, probably need to find "true" Windows machine and try it there. Thanks for reporting!

**Comment by vitalpoltava** [comment]
![2016-06-04 13 05 24](https://cloud.githubusercontent.com/assets/1306647/15799218/2d73543a-2a55-11e6-84c9-abfc7b3720e8.png)

**Comment by dovlabfs** [comment]
I just checked, I'm using the latest IE11 "Update Version 11.0.31", which is common to all Win 7 and 8 PC-s.You can see that you browser has "Update Version 11.0.27". I don't know how come there is a difference in Version code

**Comment by vitalpoltava** [comment]
At last I found a Win machine - stole from my daughter :-). Seems now the issue is fixed.

**Comment by dovlabfs** [comment]
Works like a charm. Great!
