### ISSUE TITLE
Read Only Mode & Change Rating From Controller

### ISSUE THREAD

**Issue by usman-maavan** [vitalpoltava/Star-Rating#7]
Hi,

First off all...a very good directive.
Secondly, I want to ask that how can i render this star system only to show the rating(read only mode).
Thirdly, After using stars rating i want to reset the rating to 0 by angularjs controller. For example, After a user rates an item then form values need to be cleared for 2nd time rating. i clear/default the other form values but how can i reset star rating to 0.
Thanks,

**Comment by vitalpoltava** [comment]
Hi, 

1) Thanks :)
2) To make it read-only -- just remove `rating-define` attribute when calling the directive;
3) Changing the value of the variable which you pass through `outer-percent` attribute will change the view (assigning `0` will clear the selection).

Regards,

-Vitalii

**Comment by usman-maavan** [comment]
Hi,

Thanks for the quick response.
Read only is working perfectly but when i use star rating directive on multiple Divs then it doesn't work well. I mean if i put the percent attribute of 1st div to 50 then all other Divs who are using the same directive will be marked as same rating(in this case 50).

and when from controller i am using this line.. it is not working
$scope.outerPercent = 0;
I am using this line in my page controller and directive is defined in the same controller.

Thanks,

**Comment by vitalpoltava** [comment]
Hi,

1) If you want to make several star selectors to be independent on the page, please make sure they are wrapped by different scopes -- one scope per directive.

2) `outer-percent` is NOT a scope variable -- it is a directive's attribute: 
 ```javascript
<div id="main" ng-app="stars">
    <div ng-controller="MainCtrl as mainCtrl">
        <div star-rating stars="5" outer-star-selection="stars" outer-percent="rating" rating-define="" rating-percent="50" star-radius="30" sel-color="gold" back-color="white"></div>
        <div><span ng-bind="rating"></span>%</div>
        <div><span ng-bind="stars"></span>&nbsp;stars</div>
    </div>
</div>
```
In above example you can see  attribute declaration `outer-percent="rating"` -- this means the attribute gets `rating` scope variable and `$scope.rating = 0;` should do the trick,

Regards,

-Vitalii

**Comment by usman-maavan** [comment]
Grt...Thanks
