### ISSUE TITLE
rating not working for dynamic value

### ISSUE THREAD

**Issue by gnanavelshenll** [vitalpoltava/Star-Rating#9]
Hi,

Start-rating plugin working fine with static value. like `<stars  stars="5" radius="8" stars-selected="2.5" disabled="true"></stars>`. But it is not working with dynamic value `<stars  stars="5" radius="8" stars-selected="{{ratingvalue}}" disabled="true"></stars>`. How to fix this issue?

**Comment by vitalpoltava** [comment]
Hi, can you give an example of your usage?

**Comment by gnanavelshenll** [comment]
This is what im trying. 
`<stars stars="5" radius="8" stars-selected="{{ratingvalue}}" disabled="true"></stars>`

**Comment by gnanavelshenll** [comment]
Hi vitalpoltava, Did you get this issue?

**Comment by vitalpoltava** [comment]
At the moment component just takes attribute value as an input, so it should be pre-rendered in DOM. Later I will add ability to use variables as an input source.

**Comment by gnanavelshenll** [comment]
how to add as input? It is possible to to add now?

**Comment by vitalpoltava** [comment]
Issue is fixed, thanks for your input YounesM.
